### ISSUE TITLE
Fix sonatype publish

### ISSUE THREAD

**Issue by doczir** [emartech/scala-logger#10]
Currently the project publishes it's snapshot builds among the release versions. They should be published to the snapshot repository.

**Comment by miklos-martin** [comment]
I have tried this here: emartech/jwt-akka-http@3c1f3ece57751eca64cfcca201ce71cffda9325d

That is not the way to do this :) It did not seem to have any effect.

**Comment by doczir** [comment]
This is the way the scalaz projects do it: 
https://github.com/scalaz/scalaz-logging/blob/6affac633a5d343bede32bf3b764212b8255d259/build.sbt#L7-L13

Note that they are not using sbt-release-early, so it might not work for us 😞

**Comment by miklos-martin** [comment]
I'm afraid publishTo might get overridden in the plugin or something. Otherwise, it should have had an effect. The commit I linked is effectively the same, just with more code :)

**Comment by miklos-martin** [comment]
This has been fixed in c1216d3251b55b00c3d808be4fdb94e6fe7919b4
